### ISSUE TITLE
No padding between interleaved chunks

### ISSUE THREAD

**Issue by igorciz777** [WonderfulToolchain/psxavenc#5]
using the v0.2.1 windows build from releases tab

when using the spui/vagi encoding, all the interleaved chunks don't have any padding between them

for example with this command
```shell
.\psxavenc.exe -t vagi -f 44100 -c 2 -a 0x10 -i 0x2000 .\aaaa.wav test.vag
```
the 0x10 space is only noticable between the header and the start of the adpcm data

but it is not present between the 0x2000 long interleaved chunks
![image](https://github.com/user-attachments/assets/564ba6ca-5230-4c3a-9ce6-b0ad0065c621)

this also happens without the -a parameter, with the only difference being the noticable default 0x800 padding after the header

![image](https://github.com/user-attachments/assets/eec65595-a03a-4bb2-b5ac-4b27ad4988f4)

**Comment by asiekierka** [comment]
The option `-a` doesn't pad *by* a specific amount of bytes, it pads *to* a specified amount of bytes.

Think of it like this: if you align a 33-byte buffer to a multiple of 4 bytes, that will make it 36 bytes, not 37 bytes.

**Comment by igorciz777** [comment]
oh i see, i was fooled by the fact that most of the files ive dealt with had a 0x10 blank space inbetween the chunks, which makes it easy to get the interleave value if its raw data without a header, im guessing thats probably not a standardized thing as usual lol

**Comment by asiekierka** [comment]
@spicyjpeg Got any relevant advice?

**Comment by igorciz777** [comment]
i noticed the blank 0x10 rows are actually a part of the chunks in the files im dealing with, which means i can replicate that with
```psxavenc.exe -t vagi -f 44100 -a 0x20 -c 2 -i 0x1FF0 -L .\test.m4a test.vag``` and then manually fixing the interleave back to 0x2000

note that im using this psx tool for ps2 since there is close to nothing for adpcm on spu2 and your tool is the only thing capable of making a file that plays and loops stuff properly :D
so maybe its a spu2 thing to write a blank line at the start of each chunk? anyway thanks for the help and sorry for my false report
